jms_serializer:
    metadata:
        directories:
            Demo:
                namespace_prefix: "KimaiPlugin\\DemoBundle"
                path: "@DemoBundle/Resources/config/serializer"
        warmup:
            paths:
                included:
                    - "%kernel.project_dir%/var/plugins/DemoBundle/Entity/"
