controllers:
    resource: '../../Controller/'
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

demo.api:
    resource: "@DemoBundle/API/"
    type: annotation
    prefix: /api
